---
influxdb_admin_username: admin
influxdb_admin_password: PassWord
influxdb_tls: no
influxdb_bind_address: "172.16.100.201:8086"
influxdb_users:
  - user_name: foo
    user_password: PassWord
    grants:
      - database: mydatabase
        privilege: ALL
  - user_name: write_only
    user_password: write_only
    grants:
      - database: mydatabase
        privilege: WRITE
  - user_name: read_only
    user_password: read_only
    grants:
      - database: mydatabase
        privilege: READ
  - user_name: none
    user_password: none
  - user_name: bar
    state: absent
influxdb_databases:
  - database_name: mydatabase
    state: present

influxdb_config: |
  reporting-disabled = true
  # this one is bind address for backup process
  bind-address = "127.0.0.1:8088"
  [meta]
    dir = "{{ influxdb_db_dir }}/meta"
  [data]
    dir = "{{ influxdb_db_dir }}/data"
    wal-dir = "{{ influxdb_db_dir }}/wal"
  [coordinator]
  [retention]
  [shard-precreation]
  [monitor]
  [http]
    auth-enabled = true
    bind-address = "{{ influxdb_bind_address }}"
    access-log-path = "{{ influxdb_log_dir }}/access.log"
  [ifql]
  [logging]
  [subscriber]
  [[graphite]]
  [[collectd]]
  [[opentsdb]]
  [[udp]]
  [tls]
