---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip
      - curl
cache:
  directories:
    - $HOME/.rvm/
    - $HOME/.bundler/
    - $HOME/.cache/pip/
  pip: true

matrix:
  include:
    - env:
        - TARGET_SCENARIO=travisci_ubuntu1804

before_install:
  # XXX update RubyGem to fix build in Travis CI. when ruby 2.6.3 or later is
  # available in travis environment, this can be removed.
  # see details at:
  # https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem update --system

install:
  # Install ansible
  - pip install ansible yamllint molecule docker

  # Check versions
  - ansible --version
  - molecule --version

script:
  # See if the repo is private
  - if curl --silent --output /dev/null --dump-header - "https://github.com/${TRAVIS_REPO_SLUG}" | grep "Status:[[:space:]]*404"; then touch .private_repo; fi

  # git complains if user and email are not set
  - git config --global user.name "Your Name"
  - git config --global user.email "you@example.com"

  # export PATH
  - export PATH="${PATH}:`rvm gemdir`/bin"

  # bundle up because rubocop is installed via Gemfile
  - bundle install --path ${HOME}/.bundler

  # run rubocop
  - bundle exec rubocop

  # run yamllint
  - yamllint -c .yamllint.yml .
