---
extends: default

rules:
  line-length: disable
  truthy: disable

ignore: |
  # yamllint does not understand erb template
  .kitchen.local.yml
  /.kitchen/
  /roles.galaxy/
  /playbooks/group_vars/*_credentials.yml
  /ruby/
