---

- name: trombik.hostname
  version: 1.0.5
- name: trombik.hosts
  version: 2.0.1
- name: trombik.sudo
  version: 1.0.4
- name: trombik.zsh
  version: 1.1.2
- name: trombik.vim
  version: 1.1.3
- name: trombik.tmux
  version: 1.1.3
- name: trombik.telegraf
  src: https://github.com/trombik/ansible-role-telegraf.git
  version: master
- name: trombik.influxdb
  version: 1.2.0
- name: trombik.grafana
  version: 1.1.1
